version: '3.7'


services:
  postgressql:
    image: postgres
    container_name: container_loglife
    env_file:
      - backend.env
    volumes:
      - pgdata:/data/postgres
    
 # app:
 #   build: .
 #   container_name: loglife
 #   ports: 
 #     - 3333:3333
 #   volumes:
 #     - .:/usr/app
 #   links:
 #     - postgressql
 #   depends_on:
 #     - postgressql
 #   networks:
 #     - log
    

#networks:
 #     log:
volumes:
   pgdata:
     driver: local
